[package]
name = "path"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "lib"]
name = "path"

[dependencies]
basic = { path = "../../../libs/basic", default-features = false, features = [
    "mount",
    "glob",
    "config",
] }
core = { path = "../../libcore", default-features = false }
event = { path = "../../../libs/event" }
log = { path = "../../../libs/log" }
macros = { path = "../../../libs/macros" }
constants = { path = "../../../libs/constants" }
unit_parser = { path = "../../../libs/unit_parser" }
libc = { version = "0.2.*", default-features = false }
nix = { version = "0.24", default-features = false, features = [
    "fs",
    "resource",
    "poll",
] }
once_cell = { version = "=1.8.0", default-features = false }
serde = { version = "1.0.130", default-features = false }

[features]
default = ["noplugin"]
noplugin = []
linux = []
plugin = []
