# Project information
site_name: sysmaster.online
site_url: http://sysmaster.online
site_author: dev@openeuler.org
site_description: >-
  Redesign and Reimplementation of Process1

# Repository
repo_name: openEuler/sysMaster
repo_url: https://gitee.com/openeuler/sysmaster
edit_uri: https://gitee.com/-/ide/project/openeuler/sysmaster/edit/master/-/docs/

# Copyright
copyright: Copyright &copy; 2023 openEuler sysMaster team

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: indigo
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode
    # - scheme: slate
    #   primary: indigo
    #   accent: indigo
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/git-alt

  language: zh

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true

  # - git-committers:
  #     repository: squidfunk/mkdocs-material
  #     branch: main
  # - blog

# Customization
# extra:
#   analytics:
#     provider: google
#     property: !ENV GOOGLE_ANALYTICS_KEY
  # social:
  #   # - icon: fontawesome/brands/github
  #   #   link: https://github.com/github

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
