[package]
name = "mount"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "lib"]
name = "mount"

[dependencies]
basic = { path = "../../../libs/basic", default-features = false, features = [
    "mount",
] }
core = { path = "../../libcore", default-features = false }
event = { path = "../../../libs/event" }
log = { path = "../../../libs/log" }
macros = { path = "../../../libs/macros" }
constants = { path = "../../../libs/constants", optional = true }
unit_parser = { path = "../../../libs/unit_parser" }

bitflags = { version = "1.3.2" }
epoll = "=4.3.1"
libc = { version = "0.2.*", default-features = false }
nix = { version = "0.24", default-features = false, features = [
    "fs",
    "resource",
    "poll",
    "socket",
] }
once_cell = { version = "=1.8.0", default-features = false }
serde = { version = "1.0.130", default-features = false }

[features]
default = ["noplugin", "linux"]
noplugin = []
linux = []
plugin = ["constants"]
